/*============================================================================== 
 * Copyright (c) 2012-2014 Qualcomm Connected Experiences, Inc. All Rights Reserved. 
 * ==============================================================================*/

using UnityEngine;
using System.Collections;
using System.Collections.Generic;

/// <summary>
/// All handler classes that wants to register for the events generated by ISampleAppUIView must extend this class
/// It ensures proper binding and unbinding of event listeners and other initialization and cleanup
/// </summary>
public abstract class ISampleAppUIEventHandler : MonoBehaviour {

    
    /// <summary>
    /// The following methods are exposed here for AppManager
    /// </summary>
    public abstract void TriggerAutoFocus();
}

